name: build

on:
  push:
    branches:
      - "*"
    tags:
      - "release/*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  perl:
    env:
      AUTHOR_TESTING: 1

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        perl-version:
          - "5.38"
          - "5.12"

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpm install -g --show-build-log-on-failure
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: make test
        run: make test
